source 'https://github.com/CocoaPods/Specs.git'

# workspace文件名 workspace的主工程路径，是相对于workspace的路径
workspace 'NHAVKit2Examples.xcworkspace'


target 'NHPlayExamples' do
  platform :ios, '8.0'
  project 'NHPlayExamples/NHPlayExamples.xcodeproj'

  pod 'FDFullscreenPopGesture'
  pod 'DZNEmptyDataSet'
  pod 'NHExtension'
  pod 'NHHUDExtend'

end


target 'NHCaptureExamples' do
	platform :ios, '8.0'
	project 'NHCaptureExamples/NHCaptureExamples.xcodeproj'

    pod 'FDFullscreenPopGesture'
    pod 'DZNEmptyDataSet'
    pod 'NHExtension'
    pod 'NHHUDExtend'
end
